### ISSUE TITLE
[Bug]: NoFOG mod catching errors, for underground_jungle

### ISSUE THREAD

**Issue by esvarc** [Virtuoel/NoFog#30]
### Minecraft version(s)

1.20.1

### Mod loader

Forge

### Mod loader version

1.20.1-47.2.0

### In what kind of world or server did the problem occur?

My singleplayer world

### What went wrong? (Crash logs don't go here)

1. I've installed just these two mods and Forge loader.
2. Generating new world.
3. In LOG is generated error. 
4. Underground biome seems to be fine, but I'm unable verify if NoFog is OK as well.

### Full list of installed mods and their version numbers

nofog-1.3.4_1.20.1-forge.jar
undergroundjungle-2.0.2-forge-1.20.1.jar

### Did the problem cause the game to crash?

No.

### Full crash report contents (if you experienced a crash)

<details>
<summary>log output:</summary>
<p>

```
[10:57:37] [modloading-worker-0/ERROR] [no_fog/CATCHING]: Catching
java.lang.IllegalStateException: Errors during registry creation
	at net.minecraft.core.RegistrySetBuilder$BuildState.m_255178_(RegistrySetBuilder.java:136) ~[client-1.20.1-20230612.114412-srg.jar%23358!/:?] {re:classloading,pl:rei_plugin_compatibilities:B}
	at net.minecraft.core.RegistrySetBuilder.m_255144_(RegistrySetBuilder.java:62) ~[client-1.20.1-20230612.114412-srg.jar%23358!/:?] {re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B}
	at net.minecraft.data.registries.VanillaRegistries.m_255371_(VanillaRegistries.java:72) ~[client-1.20.1-20230612.114412-srg.jar%23358!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:mixin:APP:worldgenrevisited.mixin.json:VanillaRegistriesAccessor,pl:mixin:A}
	at virtuoel.no_fog.util.ConfigUtils.populateDimensionToggles(ConfigUtils.java:54) ~[v201-nofog-1.3.4_1.20.1-forge.jar%23321!/:?] {re:classloading,pl:rei_plugin_compatibilities:B}
	at virtuoel.no_fog.util.DummyNoFogConfig.<init>(DummyNoFogConfig.java:11) ~[v201-nofog-1.3.4_1.20.1-forge.jar%23321!/:?] {re:classloading,pl:rei_plugin_compatibilities:B}
	at virtuoel.no_fog.NoFogClient.<clinit>(NoFogClient.java:28) ~[v201-nofog-1.3.4_1.20.1-forge.jar%23321!/:?] {re:classloading,pl:rei_plugin_compatibilities:B}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:70) ~[javafmllanguage-1.20.1-47.2.1.jar%23360!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:123) ~[fmlcore-1.20.1-47.2.1.jar%23359!/:?] {re:mixin}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:mixin,re:computing_frames,pl:rei_plugin_compatibilities:B}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:mixin,re:computing_frames,pl:rei_plugin_compatibilities:B}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {re:mixin}
	Suppressed: java.lang.IllegalStateException: Unreferenced key: ResourceKey[minecraft:worldgen/biome / underground_jungle:underground_jungle]
		at net.minecraft.core.RegistrySetBuilder$BuildState.m_255228_(RegistrySetBuilder.java:126) ~[client-1.20.1-20230612.114412-srg.jar%23358!/:?] {re:classloading,pl:rei_plugin_compatibilities:B}
		at net.minecraft.core.RegistrySetBuilder.m_255144_(RegistrySetBuilder.java:61) ~[client-1.20.1-20230612.114412-srg.jar%23358!/:?] {re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B}
		at net.minecraft.data.registries.VanillaRegistries.m_255371_(VanillaRegistries.java:72) ~[client-1.20.1-20230612.114412-srg.jar%23358!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:mixin:APP:worldgenrevisited.mixin.json:VanillaRegistriesAccessor,pl:mixin:A}
		at virtuoel.no_fog.util.ConfigUtils.populateDimensionToggles(ConfigUtils.java:54) ~[v201-nofog-1.3.4_1.20.1-forge.jar%23321!/:?] {re:classloading,pl:rei_plugin_compatibilities:B}
		at virtuoel.no_fog.util.DummyNoFogConfig.<init>(DummyNoFogConfig.java:11) ~[v201-nofog-1.3.4_1.20.1-forge.jar%23321!/:?] {re:classloading,pl:rei_plugin_compatibilities:B}
		at virtuoel.no_fog.NoFogClient.<clinit>(NoFogClient.java:28) ~[v201-nofog-1.3.4_1.20.1-forge.jar%23321!/:?] {re:classloading,pl:rei_plugin_compatibilities:B}
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
		at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:70) ~[javafmllanguage-1.20.1-47.2.1.jar%23360!/:?] {}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:123) ~[fmlcore-1.20.1-47.2.1.jar%23359!/:?] {re:mixin}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:mixin,re:computing_frames,pl:rei_plugin_compatibilities:B}
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:mixin,re:computing_frames,pl:rei_plugin_compatibilities:B}
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {re:mixin}

```

**Comment by sargeow** [comment]
[latest.log](https://github.com/user-attachments/files/16552825/latest.log)

same issue, same mod, while creating mod pack. however i have a separate issue that id assume is due to the same internal problem. using galosphere and no fog throws alot of errors in console but doesnt cause a crash.

EDIT: i just wanted to say your mod is the best for the needs i have and no other mod compares, so i do hope you can solve the issue at hand.
