### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Stasjon** [Virtuoel/NoFog#43]
### Minecraft version(s)

Other (specify below)

### Minecraft version details

1.21.4

### Mod loader

Fabric

### Mod loader version

Fabric loader 0.16.9

### Fabric API version

Fabric-api-0.111.9+1.21.4

### In what kind of world or server did the problem occur?

My singleplayer world

### What went wrong? (Crash logs don't go here)

It opened minecraft fine, but when i  wanted to play  SP or realm, it just crashed

### Full list of installed mods and their version numbers

![image](https://github.com/user-attachments/assets/17267940-2b6d-4dd7-b1ff-536f6bbf5f66)

### Did the problem cause the game to crash?

Yes. (paste crash report below)

### Full crash report contents (if you experienced a crash)

---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 2024-12-30 18:05:45
Description: Unexpected error

java.lang.RuntimeException: Mixin transformation of net.minecraft.class_758 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	at knot//net.minecraft.class_761.method_22710(class_761.java:469)
	at knot//net.minecraft.class_757.method_3188(class_757.java:733)
	at knot//net.minecraft.class_757.method_3192(class_757.java:493)
	at knot//net.minecraft.class_310.method_1523(class_310.java:1341)
	at knot//net.minecraft.class_310.method_1514(class_310.java:922)
	at knot//net.minecraft.client.main.Main.main(Main.java:267)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	... 13 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [no_fog.mixins.json:client.compat119plus.BackgroundRendererMixin from mod no_fog] from phase [DEFAULT] in config [no_fog.mixins.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379)
	... 16 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @Inject annotation on applyFogModifyDistance could not find any targets matching 'method_3211(Lnet/minecraft/class_4184;Lnet/minecraft/class_758$class_4596;FZF)V' in net/minecraft/class_758. No refMap loaded. [INJECT_PREPARE Applicator Phase -> no_fog.mixins.json:client.compat119plus.BackgroundRendererMixin from mod no_fog -> Prepare Injections -> handler$clk000$no_fog$applyFogModifyDistance(Lnet/minecraft/class_4184;Lnet/minecraft/class_758$class_4596;FZFLorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Parse ->  -> Validate Targets]
	at org.spongepowered.asm.mixin.injection.selectors.TargetSelectors.validate(TargetSelectors.java:346)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:369)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:340)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:331)
	at org.spongepowered.asm.mixin.injection.struct.CallbackInjectionInfo.<init>(CallbackInjectionInfo.java:48)
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:196)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:664)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1399)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:731)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:315)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:246)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:437)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:418)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 16 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	at knot//net.minecraft.class_761.method_22710(class_761.java:469)
	at knot//net.minecraft.class_757.method_3188(class_757.java:733)

-- Uptime --
Details:
	JVM uptime: 188.239s
	Wall uptime: 178.932s
	High-res time: 174.013s
	Client ticks: 3365 ticks / 168.250s
Stacktrace:
	at knot//net.minecraft.class_310.method_1587(class_310.java:2371)
	at knot//net.minecraft.class_310.method_54580(class_310.java:991)
	at knot//net.minecraft.class_310.method_1514(class_310.java:946)
	at knot//net.minecraft.client.main.Main.main(Main.java:267)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Affected level --
Details:
	All players: 1 total; [class_746['Stajon'/5, l='ClientLevel', x=398.46, y=-59.71, z=301.73]]
	Chunk stats: 961, 188
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,-60,0), Section: (at 0,4,0 in 0,-4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 203687 game time, 1417 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
	Tracked entity count: 41

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, file/Milkyway-Galaxy-Day-Night.zip, file/Invisible+Item+Frame+Pack.zip, file/Fullbright-UB-1.21.zip, file/VanillaTweaks_r320695_MC1.21.x.zip, fabric, c2me, capes, cloth-config, conditional-mixin, dynamic_fps, entity_model_features, entity_texture_features, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-language-kotlin, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-loot-api-v3, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, fabrishot, fullbright-for-mc, immediatelyfast, iris, krypton, lambdynlights, lambdynlights_api, lithium, midnightlib, modmenu, moreculling, no_fog, obsidianui, optigui, placeholder-api, pride, reeses-sodium-options, simplefog, sodium, sodium-extra, spruceui, wi_zoom, worldedit, xaerominimap, xaeroworldmap, yet_another_config_lib_v3, zoomify

-- System Details --
Details:
	Minecraft Version: 1.21.4
	Minecraft Version ID: 1.21.4
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 21.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 831019888 bytes (792 MiB) / 1577058304 bytes (1504 MiB) up to 7516192768 bytes (7168 MiB)
	CPUs: 12
	Processor Vendor: GenuineIntel
	Processor Name: 12th Gen Intel(R) Core(TM) i5-12400F
	Identifier: Intel64 Family 6 Model 151 Stepping 5
	Microarchitecture: Alder Lake
	Frequency (GHz): 2.50
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: NVIDIA GeForce RTX 4060
	Graphics card #0 vendor: NVIDIA
	Graphics card #0 VRAM (MiB): 8188.00
	Graphics card #0 deviceId: VideoController1
	Graphics card #0 versionInfo: 32.0.15.6636
	Memory slot #0 capacity (MiB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MiB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.67
	Memory slot #1 type: DDR4
	Virtual memory max (MiB): 36674.02
	Virtual memory used (MiB): 18438.60
	Swap memory total (MiB): 20480.00
	Swap memory used (MiB): 457.50
	Space in storage for jna.tmpdir (MiB): available: 500895.47, total: 976100.00
	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): available: 500895.47, total: 976100.00
	Space in storage for io.netty.native.workdir (MiB): available: 500895.47, total: 976100.00
	Space in storage for java.io.tmpdir (MiB): available: 500895.47, total: 976100.00
	Space in storage for workdir (MiB): available: 500895.47, total: 976100.00
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx7G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		c2me: Concurrent Chunk Management Engine 0.3.1+alpha.0.42+1.21.4
			c2me-base: Concurrent Chunk Management Engine (Base) 0.3.1+alpha.0.42+1.21.4
			c2me-client-uncapvd: Concurrent Chunk Management Engine (Client/Uncap View Distance) 0.3.1+alpha.0.42+1.21.4
			c2me-fixes-chunkio-threading-issues: Concurrent Chunk Management Engine (Fixes/Chunk IO/Threading Issues) 0.3.1+alpha.0.42+1.21.4
			c2me-fixes-general-threading-issues: Concurrent Chunk Management Engine (Fixes/General/Threading Issues) 0.3.1+alpha.0.42+1.21.4
			c2me-fixes-worldgen-threading-issues: Concurrent Chunk Management Engine (Fixes/WorldGen/Threading Issues) 0.3.1+alpha.0.42+1.21.4
			c2me-fixes-worldgen-vanilla-bugs: Concurrent Chunk Management Engine (Fixes/WorldGen/Vanilla Bugs) 0.3.1+alpha.0.42+1.21.4
			c2me-notickvd: Concurrent Chunk Management Engine (No Tick View Distance) 0.3.1+alpha.0.42+1.21.4
			c2me-opts-allocs: Concurrent Chunk Management Engine (Optimizations/Memory Allocations) 0.3.1+alpha.0.42+1.21.4
			c2me-opts-chunkio: Concurrent Chunk Management Engine (Optimizations/Chunk IO) 0.3.1+alpha.0.42+1.21.4
			c2me-opts-dfc: Concurrent Chunk Management Engine (Optimizations/Density Function Compiler) 0.3.1+alpha.0.42+1.21.4
			c2me-opts-math: Concurrent Chunk Management Engine (Optimizations/Math) 0.3.1+alpha.0.42+1.21.4
			c2me-opts-scheduling: Concurrent Chunk Management Engine (Optimizations/Scheduling) 0.3.1+alpha.0.42+1.21.4
			c2me-opts-worldgen-general: Concurrent Chunk Management Engine (Optimizations/General WorldGen) 0.3.1+alpha.0.42+1.21.4
			c2me-opts-worldgen-vanilla: Concurrent Chunk Management Engine (Optimizations/Vanilla WorldGen) 0.3.1+alpha.0.42+1.21.4
			c2me-rewrites-chunk-serializer: Concurrent Chunk Management Engine (Rewrites/Chunk Serializer) 0.3.1+alpha.0.42+1.21.4
			c2me-rewrites-chunk-system: Concurrent Chunk Management Engine (Rewrites/Chunk System) 0.3.1+alpha.0.42+1.21.4
			c2me-rewrites-chunkio: Concurrent Chunk Management Engine (Rewrites/Chunk IO) 0.3.1+alpha.0.42+1.21.4
			c2me-server-utils: Concurrent Chunk Management Engine (Server Utils) 0.3.1+alpha.0.42+1.21.4
			c2me-threading-lighting: Concurrent Chunk Management Engine (Threading/Lighting) 0.3.1+alpha.0.42+1.21.4
			com_electronwill_night-config_core: core 3.6.5
			com_electronwill_night-config_toml: toml 3.6.5
			com_ibm_async_asyncutil: asyncutil 0.1.0
			io_reactivex_rxjava3_rxjava: rxjava 3.1.8
			net_objecthunter_exp4j: exp4j 0.4.8
			org_jctools_jctools-core: jctools-core 4.0.5
			org_reactivestreams_reactive-streams: reactive-streams 1.0.4
		capes: Capes 1.5.4+1.21.4
		cloth-config: Cloth Config v17 17.0.144
			cloth-basic-math: cloth-basic-math 0.6.1
		dynamic_fps: Dynamic FPS 3.7.7
			net_lostluma_battery: battery 1.3.0
		entity_model_features: Entity Model Features 2.3.0
		entity_texture_features: Entity Texture Features 6.2.8
			org_apache_httpcomponents_httpmime: httpmime 4.5.10
		fabric-api: Fabric API 0.111.0+1.21.4
			fabric-api-base: Fabric API Base 0.4.53+453d4f9104
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.84+7feeb73304
			fabric-biome-api-v1: Fabric Biome API (v1) 15.0.4+466a140b04
			fabric-block-api-v1: Fabric Block API (v1) 1.0.31+7feeb73304
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.19+7feeb73304
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 2.0.7+7feeb73304
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.27+7feeb73304
			fabric-command-api-v1: Fabric Command API (v1) 1.2.61+f71b366f04
			fabric-command-api-v2: Fabric Command API (v2) 2.2.40+e496eb1504
			fabric-commands-v0: Fabric Commands (v0) 0.2.78+df3654b304
			fabric-content-registries-v0: Fabric Content Registries (v0) 9.1.12+7feeb73304
			fabric-convention-tags-v1: Fabric Convention Tags 2.1.6+7f945d5b04
			fabric-convention-tags-v2: Fabric Convention Tags (v2) 2.9.6+466a140b04
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.3.6+7feeb73304
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.4.3+9aea556b04
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 22.1.2+466a140b04
			fabric-dimensions-v1: Fabric Dimensions API (v1) 4.0.10+7feeb73304
			fabric-entity-events-v1: Fabric Entity Events (v1) 2.0.11+60fccc7604
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 4.0.1+a4eebcf004
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.62+7feeb73304
			fabric-item-api-v1: Fabric Item API (v1) 11.1.12+203e6b2304
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.1.21+7feeb73304
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.56+7feeb73304
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.54+df3654b304
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.5.3+bf2a60eb04
			fabric-loot-api-v2: Fabric Loot API (v2) 3.0.31+3f89f5a504
			fabric-loot-api-v3: Fabric Loot API (v3) 1.0.19+203e6b2304
			fabric-message-api-v1: Fabric Message API (v1) 6.0.24+7feeb73304
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 4.1.0+7b6b225304
			fabric-networking-api-v1: Fabric Networking API (v1) 4.3.8+cc0fa2fe04
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 18.0.5+e604fe7f04
			fabric-particles-v1: Fabric Particles (v1) 4.0.13+7feeb73304
			fabric-recipe-api-v1: Fabric Recipe API (v1) 8.0.3+fa62a02304
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 6.0.1+cc0fa2fe04
			fabric-renderer-api-v1: Fabric Renderer API (v1) 5.0.1+84404cdd04
			fabric-renderer-indigo: Fabric Renderer - Indigo 2.0.1+84404cdd04
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.57+73761d2e04
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.18+7feeb73304
			fabric-rendering-v1: Fabric Rendering (v1) 10.1.0+7e7568bf04
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 5.0.13+203e6b2304
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 3.0.10+203e6b2304
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.37+7feeb73304
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.106+7feeb73304
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.32+7feeb73304
			fabric-transfer-api-v1: Fabric Transfer API (v1) 5.4.6+1885ad7404
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 6.3.2+56e78b9b04
		fabric-language-kotlin: Fabric Language Kotlin 1.13.0+kotlin.2.1.0
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 2.1.0
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 2.1.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 2.1.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 2.1.0
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.26.1
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.9.0
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.9.0
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.6.1
			org_jetbrains_kotlinx_kotlinx-io-bytestring-jvm: kotlinx-io-bytestring-jvm 0.6.0
			org_jetbrains_kotlinx_kotlinx-io-core-jvm: kotlinx-io-core-jvm 0.6.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.7.3
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.7.3
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.7.3
		fabricloader: Fabric Loader 0.16.9
			mixinextras: MixinExtras 0.4.1
		fabrishot: Fabrishot 1.14.1
		fullbright-for-mc: fullbright-for-mc 1.0.0
		immediatelyfast: ImmediatelyFast 1.3.3+1.21.4
			net_lenni0451_reflect: Reflect 1.3.4
		iris: Iris 1.8.3+mc1.21.4
			io_github_douira_glsl-transformer: glsl-transformer 2.0.1
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.13.1
		java: OpenJDK 64-Bit Server VM 21
		krypton: Krypton 0.2.8
			com_velocitypowered_velocity-native: velocity-native 3.3.0-SNAPSHOT
		lambdynlights: LambDynamicLights 4.0.0+1.21.4
			lambdynlights_api: LambDynamicLights (API) 4.0.0+1.21.4
			pride: Pride Lib 1.3.0+1.21.2
			spruceui: SpruceUI 6.2.0+1.21.3
		lithium: Lithium 0.14.3+mc1.21.4
		memoryleakfix: Memory Leak Fix 1.1.5
		midnightlib: MidnightLib 1.6.6
		minecraft: Minecraft 1.21.4
		modmenu: Mod Menu 13.0.0-beta.1
		moreculling: More Culling 1.2.0-beta.2
			conditional-mixin: conditional mixin 0.6.3
			mixinsquared: MixinSquared 0.2.0
		no-telemetry: No Telemetry 1.8.0
		no_fog: No Fog 1.3.6+1.16.5-1.21
		obsidianui: ObsidianUI 0.2.10+mc1.21.3
		optigui: OptiGUI 2.3.0-beta.6+1.21.2
			org_apache_commons_commons-text: commons-text 1.12.0
			org_ini4j_ini4j: ini4j 0.5.4
		placeholder-api: Placeholder API 2.5.1+1.21.3
		reeses-sodium-options: Reese's Sodium Options 1.8.1+mc1.21.4
		simplefog: Simple Fog Control 1.7.0
		sodium: Sodium 0.6.2+mc1.21.4
		sodium-extra: Sodium Extra 0.6.1+mc1.21.4
		wi_zoom: WI Zoom 1.5-MC1.21.4
		worldedit: WorldEdit 7.3.10-beta-01+cb9fd58
		xaerominimap: Xaero's Minimap 24.7.1
		xaeroworldmap: Xaero's World Map 1.39.2
		yet_another_config_lib_v3: YetAnotherConfigLib 3.6.2+1.21.4-fabric
			com_twelvemonkeys_common_common-image: common-image 3.12.0
			com_twelvemonkeys_common_common-io: common-io 3.12.0
			com_twelvemonkeys_common_common-lang: common-lang 3.12.0
			com_twelvemonkeys_imageio_imageio-core: imageio-core 3.12.0
			com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.12.0
			com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.12.0
			org_quiltmc_parsers_gson: gson 0.2.1
			org_quiltmc_parsers_json: json 0.2.1
		zoomify: Zoomify 2.14.2+1.21.3
			com_akuleshov7_ktoml-core-jvm: ktoml-core-jvm 0.5.2
	Loaded Shaderpack: (off)
	Launched Version: fabric-loader-0.16.9-1.21.4
	Launcher name: minecraft-launcher
	Backend library: LWJGL version 3.3.3-snapshot
	Backend API: NVIDIA GeForce RTX 4060/PCIe/SSE2 GL version 3.2.0 NVIDIA 566.36, NVIDIA Corporation
	Window size: 1920x1009
	GFLW Platform: win32
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Universe: 400921fb54442d18
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Render Distance: 12/12 chunks
	Resource Packs: vanilla, file/Milkyway-Galaxy-Day-Night.zip (incompatible), file/Invisible+Item+Frame+Pack.zip (incompatible), file/Fullbright-UB-1.21.zip (incompatible), file/VanillaTweaks_r320695_MC1.21.x.zip (incompatible), fabric, c2me, capes, cloth-config, conditional-mixin, dynamic_fps, entity_model_features, entity_texture_features, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-language-kotlin, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-loot-api-v3, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, fabrishot, fullbright-for-mc, immediatelyfast, iris, krypton, lambdynlights, lambdynlights_api, lithium, midnightlib, modmenu, moreculling, no_fog, obsidianui, optigui, placeholder-api, pride, reeses-sodium-options, simplefog, sodium, sodium-extra, spruceui, wi_zoom, worldedit (incompatible), xaerominimap (incompatible), xaeroworldmap (incompatible), yet_another_config_lib_v3 (incompatible), zoomify
	Current Language: en_us
	Locale: en_US
	System encoding: Cp1252
	File encoding: UTF-8
	CPU: 12x 12th Gen Intel(R) Core(TM) i5-12400F
	Server Running: true
	Player Count: 1 / 8; [class_3222['Stajon'/5, l='ServerLevel[New World]', x=398.46, y=-59.71, z=301.73]]
	Active Data Packs: vanilla, fabric, fabric-convention-tags-v2
	Available Data Packs: fabric, fabric-convention-tags-v2, minecart_improvements, redstone_experiments, trade_rebalance, vanilla
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	World Seed: 906446846008111978
	Suppressed Exceptions: ~~NONE~~

**Comment by kab45** [comment]
Same :(
I also have a pretty similar list of mods, so it's very likely that
