### ISSUE TITLE
Crashes when i go in a bubble column 

### ISSUE THREAD

**Issue by bstar16** [Virtuoel/NoFog#9]
Version - 1.16.4

java.lang.NoSuchFieldError: field_15517
	at net.minecraft.class_758.handler$zgp000$applyFogModifyDensity(class_758.java:529)
	at net.minecraft.class_758.method_3211(class_758.java:204)
	at net.minecraft.class_761.method_22710(class_761.java:1128)
	at net.minecraft.class_757.method_3188(class_757.java:727)
	at net.minecraft.class_757.method_3192(class_757.java:546)
	at net.minecraft.class_310.method_1523(class_310.java:1048)
	at net.minecraft.class_310.method_1514(class_310.java:681)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_758.handler$zgp000$applyFogModifyDensity(class_758.java:529)
	at net.minecraft.class_758.method_3211(class_758.java:204)
	at net.minecraft.class_761.method_22710(class_761.java:1128)
	at net.minecraft.class_757.method_3188(class_757.java:727)

**Comment by bstar16** [comment]
i know its not latest ver but yeah

**Comment by Tommeh1** [comment]
Please provide your entire crash report, either as a file or by uploading/pasting it to somewhere and linking to it.

**Comment by Virtuoel** [comment]
Reproduced on 1.16.5.
